vendor: xilinx: open-amp-xlnx: Fix lopper task dependencies
Lopper needs to run AFTER do_unpack, otherwise the the yaml file might not be
available, and result in the error:
   Error: input file openamp-overlay-zynqmp.yaml does not exist

Signed-off-by: Mark Hatle <mark.hatle@amd.com>